trainingInput:
  scaleTier: BASIC_GPU
  jobDir: gs://LSTM
  moduleName: char_lstm.py
  packagePath: .


gcloud ml-engine jobs submit training ML_20180830_212130 \
--package-path . \
--module-name char_lstm.py \
--region $REGION \
--job-dir gs://ml_train_data/LSTM \
-- \
--train-file anna.txt \
--batch-size 64       \
--seq-len 200         \
--num-units 512       \
--num-layers 1        \
--num-epoches 10      \
--check-point 5       \
--output-file output.txt